using System.Collections;
using System.Collections.Generic;
using System;
using UnityEngine;
using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.DocumentModel;
using Amazon.DynamoDBv2;

namespace TriviaGame
{
    public enum Category
    {
        Science_and_Nature,
        Entertainment,
        Geography,
        History,
        Arts_and_Literature,
        Sports_and_Leisure
    }

    //[DynamoDBTable("TriviaGame")]
    [Serializable]
    public class Question : IQuestion
    {
        public string id { get; set; }

        public Category category { get; set; }

        public string questionText { get; set; }

        public List<Answer> answerList { get; set; }

        public List<string> EnteredAnswersList { get; set; }

        // 0 parameter constructor required for DynamoDB
        public Question() { }

        public Question(string questionText)
        {
            this.questionText = questionText;

            answerList = new List<Answer>();
            EnteredAnswersList = new List<string>();
            //Category = new HashSet<Category>();
        }

        public void AddAnswer(params string[] answerPermutations)
        {
            List<string> lst = new List<string>(answerPermutations);

            Answer answerEntry = new Answer(lst);
            
            answerList.Add(answerEntry);
        }

        public void AddAnswer(List<string> answerPermutations)
        {
            Answer answerEntry = new Answer(answerPermutations);

            answerList.Add(answerEntry);
        }

        public string GetQuestionText()
        {
            return questionText;
        }

        public string CheckAnswer(string answer)
        {
            foreach (Answer answerEntry in answerList)
            {
                string checkedAnswer = answerEntry.CheckAnswer(answer);

                if (checkedAnswer != null)
                {
                    return checkedAnswer;
                }
            }

            return null;
        }

        public int AnswersRemainingCount()
        {
            return answerList.Count;
        }

        public int TotalAnswersCount()
        {
            return answerList.Count + EnteredAnswersList.Count;
        }

        public int EnteredAnswersCount()
        {
            return EnteredAnswersList.Count;
        }

        public void RemoveAnswer(string toRemove)
        {
            foreach (Answer answerEntry in answerList)
            {
                string checkedAnswer = answerEntry.CheckAnswer(toRemove);

                if (checkedAnswer != null)
                {
                    answerList.Remove(answerEntry);
                    EnteredAnswersList.Add(checkedAnswer);
                    return;
                }
            }
        }

        // returns AnswerList formatted as string for easy serialization
        public string AnswersAsString()
        {
            string data = "";

            foreach (Answer answer in answerList)
            {
                foreach (string answerPermutation in answer)
                {
                    data += answerPermutation + ";";
                }
                data = data.Remove(data.Length - 1);
                data += "|";
            }
            if (data.Length > 0)
                data = data.Remove(data.Length - 1);

            return data;
        }

        // answerString = string generated by AnswersAsString()
        public void SetAnswersFromString(string answerString)
        {
            answerList = new List<Answer>();

            string[] answerGroup = ((string)(answerString)).Split(new string[] { "|" }, StringSplitOptions.None);

            foreach (string answer in answerGroup)
            {
                string[] allPermutations = ((string)(answer)).Split(new string[] { ";" }, StringSplitOptions.None);
                Answer finishedAnswer = new Answer(new List<string>(allPermutations));
                answerList.Add(finishedAnswer);
            }
        }

        public string EnteredAnswersAsString()
        {
            Debug.Log(EnteredAnswersList);
            string data = "";

            foreach (string answer in EnteredAnswersList)
            {
                data += answer + "|";
            }
            if (data.Length > 0)
                data = data.Remove(data.Length - 1);

            return data;
        }

        public void SetEnteredAnswersFromString(string answers)
        {
            if (answers == "" || answers == null)
            {
                EnteredAnswersList = new List<string>();
                return;
            }
            Debug.Log("answers = " + answers);

            string[] answerGroup = answers.Split(new string[] { "|" }, StringSplitOptions.None);

            EnteredAnswersList = new List<string>(answerGroup);
        }

        public static List<Question> JsonToQuestions(string json)
        {
            QuestionStructList qStructs = JsonUtility.FromJson<QuestionStructList>("{\"questions\":" + json + "}");

            List<Question> questions = new List<Question>();

            foreach (QuestionStruct qStruct in qStructs.questions)
            {
                questions.Add(QuestionStructToQuestion(qStruct));
            }
            return questions;
        }

        public static string QuestionToJson(Question question)
        {
            var qStruct = new QuestionStruct();
            qStruct.id = question.id.ToString();
            qStruct.questionText = question.questionText;
            qStruct.category = question.category.ToString();
            qStruct.answerList = question.AnswersAsString();
            //qStruct.answerList = JsonUtility.ToJson(question.answerList);
            qStruct.enteredAnswers = question.EnteredAnswersAsString();

            Debug.Log("JUTIL = " +JsonUtility.ToJson(qStruct));
            return JsonUtility.ToJson(qStruct, false);
        }

        public static Question JsonToQuestion(string json)
        {
            Debug.Log(json);
            QuestionStruct qStruct = JsonUtility.FromJson<QuestionStruct>(json);

            return QuestionStructToQuestion(qStruct);
        }

        private static Question QuestionStructToQuestion(QuestionStruct qStruct)
        {
            Question question = new Question();
            question.id = qStruct.id;
            Debug.Log("id = " + qStruct.id);
            question.questionText = qStruct.questionText;
            Debug.Log("qT = " + qStruct.questionText);
            question.category = (Category)Enum.Parse(typeof(Category), qStruct.category);
            Debug.Log("cat = " + qStruct.category);
            question.SetAnswersFromString(qStruct.answerList);
            Debug.Log("answers = " + qStruct.answerList);
            question.SetEnteredAnswersFromString(qStruct.enteredAnswers);

            return question;
        }

        [Serializable]
        private struct QuestionStruct
        {
            public string id;
            public string questionText;
            public string category;
            public string answerList;
            public string enteredAnswers;
        }

        [Serializable]
        private struct QuestionStructList
        {
            public List<QuestionStruct> questions;
        }
    }
    
}
